version: "3"

services:
  mongodb:
    image: mongo:5.0.7
    container_name: docker_mongoDB
    restart: always
    ports:
      - 27017:27017
  mysqldb:
    image: mysql:5.7
    container_name: docker_MySQLDB
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=create_personDB
    restart: always
    ports:
      - 3306:3306