const responseFrontCreate = {
  userId: 1,
  nome: 'fulano',
  raça: 'humano',
  idade: 0,
  vida: 0,
  magia: 0,
  xp: 0,
  imagem: 'imagem',
  historia: 'ele e um bom homem',
  atributos: {
    força: 0,
    habilidade: 0,
    resistencia: 0,
    inteligencia: 0,
    armadura: 0,
  },
  habilidades: [],
  magias: [],
  vantagens: [],
  desvantagens: [],
  equipamento: [],
};

const returnDBCreate = {
  id: '6348513f34c397abcad040b2',
  userId: 1,
  nome: 'fulano',
  raça: 'humano',
  idade: 0,
  vida: 0,
  magia: 0,
  xp: 0,
  imagem: 'imagem',
  historia: 'ele e um bom homem',
  atributos: {
    força: 0,
    habilidade: 0,
    resistencia: 0,
    inteligencia: 0,
    armadura: 0,
  },
  habilidades: [],
  magias: [],
  vantagens: [],
  desvantagens: [],
  equipamento: [],
};
const returnDBFindAll = [
  {
  id: '6348513f34c397abcad040b2',
  userId: 1,
  nome: 'fulano',
  raça: 'humano',
  idade: 0,
  vida: 0,
  magia: 0,
  xp: 0,
  imagem: 'imagem',
  historia: 'ele e um bom homem',
  atributos: {
    força: 0,
    habilidade: 0,
    resistencia: 0,
    inteligencia: 0,
    armadura: 0,
  },
  habilidades: [],
  magias: [],
  vantagens: [],
  desvantagens: [],
  equipamento: [],
},
{
  id: '64865874f34c397abcad040b2',
  userId: 1,
  nome: 'siclano',
  raça: 'humano',
  idade: 0,
  vida: 0,
  magia: 0,
  xp: 0,
  imagem: 'imagem',
  historia: 'ele ja foi um bom homem',
  atributos: {
    força: 0,
    habilidade: 0,
    resistencia: 0,
    inteligencia: 0,
    armadura: 0,
  },
  habilidades: [],
  magias: [],
  vantagens: [],
  desvantagens: [],
  equipamento: [],
},
];
const returnDBUpdate = {
  id: '6348513f34c397abcad040b2',
  userId: 1,
  nome: 'fulano',
  raça: 'lagarto',
  idade: 0,
  vida: 0,
  magia: 0,
  xp: 0,
  imagem: 'imagem',
  historia: 'ele e um bom homem',
  atributos: {
    força: 0,
    habilidade: 0,
    resistencia: 0,
    inteligencia: 0,
    armadura: 0,
  },
  habilidades: [],
  magias: [],
  vantagens: [],
  desvantagens: [],
  equipamento: [],
};
const responseFrontUpdate = {
  id: '6348513f34c397abcad040b2',
  userId: 1,
  nome: 'fulano',
  raça: 'humano',
  idade: 0,
  vida: 0,
  magia: 0,
  xp: 0,
  imagem: 'imagem',
  historia: 'ele e um bom homem',
  atributos: {
    força: 0,
    habilidade: 0,
    resistencia: 0,
    inteligencia: 0,
    armadura: 0,
  },
  habilidades: [],
  magias: [],
  vantagens: [],
  desvantagens: [],
  equipamento: [],
};
module.exports = {
  responseFrontCreate,
  responseFrontUpdate,
  returnDBCreate,
  returnDBFindAll,
  returnDBUpdate,
};